<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Program.Naive.cs" />
		<None Include="Program.Naive.cs" />
	</ItemGroup>

	<ItemGroup Condition="Exists('../../../JsonPit/JsonPit.csproj')">
		<ProjectReference Include="../../../JsonPit/JsonPit.csproj" />
		<ProjectReference Include="../../../OsLib/OsLib.csproj" />
	</ItemGroup>

	<ItemGroup Condition="Exists('../../JsonPit/JsonPit.csproj') and !Exists('../../../JsonPit/JsonPit.csproj')">
		<ProjectReference Include="../../JsonPit/JsonPit.csproj" />
		<ProjectReference Include="../../OsLib/OsLib.csproj" />
	</ItemGroup>

	<ItemGroup Condition="!Exists('../../../JsonPit/JsonPit.csproj') and !Exists('../../JsonPit/JsonPit.csproj')">
		<PackageReference Include="JsonPit" Version="4.5.5" />
		<PackageReference Include="OsLibCore" Version="4.5.5" />
	</ItemGroup>
</Project>
